name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        include:
          - python: "3.6"
            env: py36-django32
            os: ubuntu-20.04  # 3.6 is not available on ubuntu-20.04
          - python: "3.8"
            env: py38-django32
          - python: "3.10"
            env: py310-django32

          - python: "3.8"
            env: py38-django40
          - python: "3.9"
            env: py39-django40
          - python: "3.10"
            env: py310-django40

          - python: "3.9"
            env: py39-django41
          - python: "3.10"
            env: py310-django41
          - python: "3.11"
            env: py311-django41

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python -m pip install -e .
          pip install tox tox-gh-actions
      - name: Run tests using tox
        run: tox -e ${{ matrix.env }}