name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        include:
          - python: "3.7"
            env: py37-django11
            os: ubuntu-20.04  # 3.7 is not available on ubuntu-latest
          - python: "3.8"
            env: py38-django11

          - python: "3.8"
            env: py38-django21
          - python: "3.9"
            env: py39-django21

          - python: "3.8"
            env: py38-django32
          - python: "3.9"
            env: py39-django32
          - python: "3.10"
            env: py310-django32

          - python: "3.8"
            env: py38-django40
          - python: "3.9"
            env: py39-django40
          - python: "3.10"
            env: py310-django40

          - python: "3.9"
            env: py39-django41
          - python: "3.10"
            env: py310-django41
          - python: "3.11"
            env: py311-django41

          - python: "3.9"
            env: py39-django42
          - python: "3.10"
            env: py310-django42
          - python: "3.11"
            env: py311-django42

          - python: "3.10"
            env: py310-django50
          - python: "3.11"
            env: py311-django50
          - python: "3.12"
            env: py312-django50

          - python: "3.10"
            env: py310-django51
          - python: "3.11"
            env: py311-django51
          - python: "3.12"
            env: py312-django51

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          sh build.sh
          pip install tox tox-gh-actions
      - name: Run tests using tox
        run: tox -e ${{ matrix.env }}
